language: node_js
node_js:
- '7'
script:
- npm run build
install:
- npm install
before_deploy:
- curl -fSL "https://releases.hashicorp.com/terraform/0.9.11/terraform_0.9.11_linux_amd64.zip"
  -o terraform.zip
- sudo unzip terraform.zip -d /opt/terraform
- sudo ln -s /opt/terraform/terraform /usr/bin/terraform
- rm -f terraform.zip
deploy:
- provider: script
  skip_cleanup: true
  script: ./deploy.sh
env:
  global:
  - secure: SZM6g+AnWmZJHhh18YN8xzoGJm02DXJ7wA97xdA1yUq2ngBNXGNkh4cC0YAx/kFD7Uwdsw8XQG0oR6LpjYte6u5wSaKap++QpBUbW8Ywl1CvYU9//901FigtMndbvzsDzBPFhv2iF4VNOEcwiAQl8dZlTmHwOiX60jINCUEy+pfNvrpjS8/6DThPYcxJA+fyTFrRVVviwqsk2xc9jv5cPHVfkbZr0rwuwZHiM8AiJhEsuhlwfYiqP6LZ6d5ZdYsUv5OYTGWmXHthe2J6yASjoFp+XSXpDMPOiw79XXRcC8LKndrGaiH5K513ZHT1Pq+PwUBgCs3hbbdPLV41+ARw39twYCnGdZv5RQfySb92P4VePwCR5Y8ZR0+LF4AVW3pb4pPyg+l5aMqn2wPgfjqGwapkfjAHB6iX7ynwTMrow0F4zL7C9jqv4TKjW+X+s6aoCf9kk89HOlBge0YG8wohNWnu34ezBC1eowAeqtCKD7ePdRljAQF7k0nxvvX49nvtCMkkmcXpWd1m6hAGu0waD3Qu+GyM9DRmnRSIehjpCNdSlUSEqD2W79yGWfoJ4ddvnrkSboHeOlVKnEX2QQhHVzuMYfNLmJbSnoIEqPzyX87wdb3+5rDnLGHKo1I4iFhuwZT7yrb8oPDzNTbPDZD3FhLD6qcIB/G9ISJq6IMiadg=
  - secure: YdRCSXVNIG/OfCgqhOT2N5gHyXBhGOThgXB8LvAPPQe1emTVLquY3oCHRp/Z3nDk3ehd0ZidJ1g1xEUj+YWdrdpG9NUeVn8LjsJMDsgEkc3lX6GsHgGlvmbPkrUWLGavICI3v29k+hsb/laN7E9irjVhYrVsXmcEPG5otpop3ojrb4hnmRD2u0W2jOo5truj8TD29KxjZWz39VlQfTLWBgnJ2vOZm6GKnwgAuxRj5VMg1zys7MyDlUeeNtIhffWEqiOVobvhWQn5H+xDkr3Ev3gOWvqAXb8QB7NOs/c7SXoziSPrDsV7PgQmuZVIBpaIHEbzeJpjsFyLpjn4j3PQtIna/YVKBhlC5rceNCnmJI8g+OHayE7c51ZgJyqEuls9Ev2tPtIKKMI86GqhNfQcC9MSJYroAX8tnIXm/+Aop8B07Ws+n2o3MAIBzcim1wBjUQVNnLAwE1cWwZowy+hvySkm6AGL14POFJbO7pS5pZLC+c2oS3c72fCyBAI0Eeki+xig4chbasNvDlAuuG26urzv3jMOIc74+t8JsX8PSQhYy9CMPG0kn6kMyR30r+6xJ+x1E9zydDVqlBStMumUd9emqVmgMKdY4zxajRB5CDg+yVaRWRRFBknniXt11UplH7AijDW74bk0MVfrD0Lapj47DBF6cXat5gYTkA7ri/k=
  access_key:
    secure: AqY0jrXIWTtriL2Nh0W5k+H6se/N2h2QFLYXqYniuX5hD4CkGCv9puayqnA82e1qR6dFKXmQvlDFmjjoQ3f68qrvxV3jzaqMVLzGHfLCkWSLRB9BvpzgxCdy9sOYaMM+yhaXeZigxMPRoE5H5Z3f5R95BTUpAjAWZ4JH2vToi2NHWoEgC+MawrsD38AwXwfSXiptsK4UTNMQ7jv34vaeo8+mErmdZ2s06LIGqyHYIJsj56M+FNGK4i2ZfwNYhzUJnxrm1SMTlOsN8o4PA3jOTPOyP+n+mGKYiBYHQtsY/CDxQBuEOl7MUXxKMUJMAvZGtqn2dxzrL3kmcBJUcZzfeeRG6QrsQKqfdwNHD+XVk+miXf96fU/IU3IFZ6gutx7WKujlftcVKpdZp6Vtewo4mMb8OjcK8BaMS7qlOTdzu7Py+hz98jA5GON9bdWYOW2yHIRp6L4P/exCn+GRwtKOcm6TVvPJ2EzGC6yHTUbxxvEW8AJu+ODxlT0J58HXBfLXn6/ar5Uk33Tz5tJzJS9HYs/snGpLG3JKQdqyFrkkPGyp5eKCA+uqsC6fn/gpVd+KCsTX+4SGJ7SVOPjMYReyIx5nWO2wHCkyujWaHZhN7LqFwQRMu5t55I+D/awA1LNE+wZTnpNtCayHqB46qO0QxdKc2T1I0Lkc2pBaxCACV4Q=
